### ISSUE TITLE
New Feature: Spirit Jar

### ISSUE THREAD

**Issue by VoidTest** [klikli-dev/occultism-feature-tracker#28]
I dont like how the crushing spirits have to be entities in the world and i have to drop the items. This is quite laggy if scaled up. I suggest making a spirit jar where a spirit can be placed inside and then the ores and stuff can be piped in and dust can be piped out. This would still fit the theme of the mod and but MUCH less laggy and scalable.

**Comment by klikli-dev** [comment]
@VoidTest that is a valid concern. There is an addon mod that makes this possible by using Ars Nouveau: https://legacy.curseforge.com/minecraft/mc-mods/ars-ocultas
