### ISSUE TITLE
[1.21] [NeoForge] chalk bag

### ISSUE THREAD

**Issue by delta2k** [klikli-dev/occultism-feature-tracker#29]
Would love to see a chalk bag. My inventory. Getting full of chalks. Would like them in a bag that we can scroll through them and also repair them in the bag with XP or items.  Possible? Thanks

**Comment by klikli-dev** [comment]
The ritual satchels fulfill most of that role (with the addon of also placing the chalks for you auutomatically), except for the repairing. Repairing or making them not consume durability is currently actively being discussed, so I am closing this issue
